[package]
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"
keywords = ["git", "cli", "conventional-commits", "conventional", "commits"]
license-file = "LICENSE"
name = "cc-cli"
readme = "README.md"
repository = "https://github.com/sousandrei/cc-cli"
version = "0.1.0"

[dependencies]
anyhow = "1.0.43"
argh = "0.1.5"
inquire = "0.0.6"
