name: Branches

on:
  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo fmt --all -- --check
      - run: cargo clippy --release -- -D warnings
      - run: cargo build --release