name: Main

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo fmt --all -- --check
      - run: cargo clippy --release -- -D warnings
      - run: cargo build --release

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          release-type: rust
